name: Code Formatting
on:
  workflow_dispatch:

env:
  TARGET_FILE: "_site/**/*.html"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Iron"

      - name: Format
        run: npm i --no-save prettier && npx prettier --write ${{ env.TARGET_FILE }}

      - name: debug
        run: cat -A ./_site/index.html
