name: Create Another Repo PR
on:
  push:
    branches:
      - main
jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Generate Token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: actions/github-script@v3
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            const result = await github.rest.repos.getContent({
                owner: "doubutsunokarada",
                repo: "dodosuko",
                path: 'ddsk.py'
              })
            console.log(result);
