name: Project Builder
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  TARGET_FILE: "_output/**/*.html"

jobs:
  lume-build:
    name: Lume Build & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.42.1

      - name: Build
        run: deno task lume --dest _output

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Iron"

      - name: Format
        run: npx prettier --write ${{ env.TARGET_FILE }}

      - name: debug
        run: cat -A ./_output/index.html

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git switch -c build/${{ env.CURRENT_DATETIME }}
          git push -u origin build/${{ env.CURRENT_DATETIME }}

      - name: Add and Commit
        uses: EndBug/add-and-commit@v9
        with:
          add: "_output"
          message: "commit date: ${{ env.CURRENT_DATETIME }}"
          push: true

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --base "output" --title "Output ${{ env.CURRENT_DATETIME }}" --body "Created at ${{ env.CURRENT_DATETIME }}"
