name: Project Builder
on:
  push:
    branches:
      - main

env:
  TARGET_FILE: "_site/**/*.html"

jobs:
  lume-build:
    name: Lume Build & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.42.1

      - name: Build
        run: deno task lume --dest _output

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Iron"

      - name: Format
        run: npx prettier --write ${{ env.TARGET_FILE }}

      - name: debug
        run: cat -A ./_site/index.html
