name: Project Builder
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

env:
  TARGET_FILE: "*.html"

jobs:
  lume-build:
    name: Lume Build & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.42.1

      - name: Configure Git
        run: |
          git config user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git pull

      - name: Build
        run: |
          deno task lume --dest _output
          mv ./_output ${{ runner.temp }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Iron"

      - name: Format
        working-directory: ${{ runner.temp }}/_output
        run: npx prettier ${{ env.TARGET_FILE }} --write

      - name: Set current datetime as env variable
        env:
          TZ: "Asia/Tokyo"
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: build/${{ env.CURRENT_DATETIME }}
        run: |
          git branch
          git switch output
          git switch -c ${{ env.BRANCH_NAME }}
          git push -u origin ${{ env.BRANCH_NAME }}

      - name: Move _output back
        run: |
          rm -rf ./_output
          mv ${{ runner.temp }}/_output .

      - name: Add and Commit
        run: |
          git add _output
          git status
          git commit -m "commit date: ${{ env.CURRENT_DATETIME }}"
          git push

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr create --base "output" --title "Output ${{ env.CURRENT_DATETIME }}" --body "Created at ${{ env.CURRENT_DATETIME }}"
