name: Upload Artifact
on:
  push:
    branches:
      - output

jobs:
  save-artifact:
    name: Save Artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Archive output directory
        run: |
          zip -r ${{ runner.temp }}/_output.zip _output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: output
          path: ${{ runner.temp }}/_output.zip
